
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from "@/app/components/header";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header></Header>
      {children}
      {/*<footer className='bg-amber-400 p-4'>*/}
      {/*    <p>Footer</p>*/}
      {/*</footer>*/}
      </body>
    </html>
  )
}
